/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;
import java.awt.Color;

/**
 *
 * @author Vilaris
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        jMenuBar1.setBackground (new
        Color(25, 55, 100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        menuCadastrarHospede = new javax.swing.JMenuItem();
        menuConcularHospede = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        menuCadastrarQuartos = new javax.swing.JMenuItem();
        menuConsultarQuartos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIGEP - Tela Principal");

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 255));

        jMenu1.setBackground(new java.awt.Color(51, 29, 239));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/registration_card_icon_177255 (1).png"))); // NOI18N
        jMenu1.setText("Cadastros");

        jMenu9.setText("Hospedes");

        menuCadastrarHospede.setText("Cadastrar");
        jMenu9.add(menuCadastrarHospede);

        menuConcularHospede.setText("Consultar");
        menuConcularHospede.addActionListener(this::menuConcularHospedeActionPerformed);
        jMenu9.add(menuConcularHospede);

        jMenu1.add(jMenu9);

        jMenu10.setText("Quartos");

        menuCadastrarQuartos.setText("Cadastrar");
        menuCadastrarQuartos.addActionListener(this::menuCadastrarQuartosActionPerformed);
        jMenu10.add(menuCadastrarQuartos);

        menuConsultarQuartos.setText("Consultar");
        jMenu10.add(menuConsultarQuartos);

        jMenu1.add(jMenu10);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reservas");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Consumo");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Finanças");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Relatórios");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Segurança");
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Ferramentas");
        jMenuBar1.add(jMenu7);

        menuSair.setText("Sair");
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 767, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuConcularHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConcularHospedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuConcularHospedeActionPerformed

    private void menuCadastrarQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarQuartosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastrarQuartosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuCadastrarHospede;
    private javax.swing.JMenuItem menuCadastrarQuartos;
    private javax.swing.JMenuItem menuConcularHospede;
    private javax.swing.JMenuItem menuConsultarQuartos;
    private javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables
}
